spring:
    application.name:
        inteface_check_in

    datasource:
        url: jdbc:postgresql://localhost:5432/nome_do_banco
        username: seu_usuario
        password: sua_senha
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update  # ou validate, create, create-drop, conforme sua necessidade
        show-sql: true
        properties:
            hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    servlet:
        context-path: /${spring.application.name}
    port: 8080
    # SSL (Secure Sockets Layer) é um protocolo de segurança que estabelece uma conexão criptografada entre um cliente (como um navegador) e um servidor.
    ssl:
        enabled: false