spring:
  application:
    name: inteface_check_in  # Nome da aplicação Spring Boot

  datasource:
    url: jdbc:sqlite:database.sqlite  # Caminho do arquivo do banco de dados SQLite
    driver-class-name: org.sqlite.JDBC  # Classe do driver JDBC para SQLite

  jpa:
    hibernate:
      ddl-auto: update  # Atualiza automaticamente o schema do banco conforme as entidades Java
    show-sql: true  # Mostra as queries SQL geradas pelo Hibernate no console
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect  # Dialeto oficial do Hibernate para SQLite (Hibernate 6.x)

server:
  servlet:
    context-path: /${spring.application.name}  # Define o contexto da aplicação usando o nome definido acima
  port: 8080  # Porta em que o servidor irá rodar
  ssl:
    enabled: false  # SSL desabilitado (aplicação rodando sem criptografia)
